README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_id.md, README_nl.md, README_pl.md, README_ru.md, README_zh_Hans.md, manifest.toml
=> Upgrade to v25.3.7 (autoupdate)

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_id.md, README_nl.md, README_pl.md, README_ru.md, README_zh_Hans.md, manifest.toml
=> Upgrade addons source (auto-update)

README.md, README_ca.md, README_de.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_id.md, README_nl.md, README_pl.md, README_ru.md, README_zh_Hans.md, manifest.toml
Upgrade sources
- `main` v25.3.30: https://codeberg.org/fortified/forte/releases/tag/25.3.30
=> Upgrade to v25.3.30

README.md, manifest.toml
=> Upgrade to v25.5.12.2 (auto-update)

README.md, manifest.toml
=> Update to 25.5.14

README.md, manifest.toml
=> Update to 25.5.14.1

README.md, manifest.toml
=> Update to 25.5.14.2

README.md, manifest.toml
=> Update to 25.5.17.1

README.md, manifest.toml
=> Upgrade to v25.6.7 (auto-update)

README.md, manifest.toml
=> Update to v25.6.9

README.md, manifest.toml
=> Upgrade to v25.6.14 (auto-update)

README.md, manifest.toml
=> Upgrade to v25.6.18 (auto-update)

README.md, manifest.toml
=> Upgrade to v25.6.24 (auto-update)

README.md, manifest.toml, scripts/install
=> Upgrade to v25.7.14 

README.md, manifest.toml
=>  Upgrade to v25.7.18

README.md, manifest.toml
=> Upgrade to v25.7.22 (auto-update)

README.md, manifest.toml
=> Upgrade to v25.8.4

README.md, manifest.toml
=> Upgrade to v25.8.22 (auto-update)

README.md, manifest.toml, scripts/_common.sh, scripts/install, scripts/upgrade, tests.toml
=> Upgrade to v25.9.3

README.md, manifest.toml
=> Update from dev (possible OWA fix) 
